about: {documentation: https://docs.microsoft.com/en-us/cli/azure, homepage: https://github.com/Azure/azure-cli, license: MIT, license_file: LICENSE, repository: https://github.com/Azure/azure-cli, summary: Microsoft Azure Command-Line Tools Core Module}
build: {noarch: python, number: 0, script: '${{ PYTHON }} -m pip install . --no-deps -vv'}
context: {name: azure-cli-core, version: 2.76.0}
extra:
  recipe-maintainers: [dhirschfeld, andreyz4k, janjagusch]
package: {name: '${{ name|lower }}', version: '${{ version }}'}
requirements:
  host: ['python ${{ python_min }}.*', pip, python]
  run: ['python >=${{ python_min }}', 'azure-mgmt-core >=1.2.0,<2', cryptography, distro, jmespath, msal ==1.33.0b1, packaging >=20.9, pkginfo >=1.5.0.1, psutil >=5.9, py-deviceid, pyjwt >=2.1.0, pyopenssl >=17.1.0, requests, 'knack >=0.11.0,<0.12.dev0', 'humanfriendly >=10.0,<11.dev0', 'argcomplete >=3.5.2,<3.6.dev0', 'microsoft-security-utilities-secret-masker
        >=1.0.0b4,<1.1.dev0', python, msal-extensions ==1.2.0, azure-cli-telemetry ==1.1.0.*]
schema_version: 1
source: {sha256: 97dbcc4557589cb68356d9f5c3793ecf5d86118622dc78835057e029c7698a95, url: "https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz"}
tests:
  - python:
      imports: [azure, azure.cli, azure.cli.core, azure.cli.core.commands, azure.cli.core.extension, azure.cli.core.profiles]
      python_version: ${{ python_min }}.*
